"""
core/slack.py
-------------
Centralized Slack notification helper for the AI Brain pipeline.

PRODUCTION BEHAVIOUR:
    Posts rich Block Kit messages to configured Slack channels via
    Incoming Webhooks. Different channels are used per notification type:
      - #alerts-urgent    → URGENT WhatsApp issues needing immediate response
      - #content-approval → SEO blog drafts awaiting human approval
      - #ads-insights     → Ad split-test recommendations

MOCK BEHAVIOUR:
    Logs a formatted preview of the Slack payload to stdout, simulating
    exactly what the webhook call would send.

Usage:
    from core.slack import slack
    slack.send_urgent_alert(message_record)
    slack.send_content_approval(draft_record)
    slack.send_ad_recommendation(campaign_name, ideas)
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from typing import Any

import requests

from config import settings

logger = logging.getLogger(__name__)


@dataclass
class SlackPayload:
    """Structured Slack Block Kit payload."""
    channel_url: str
    text: str                        # Fallback plain-text (notifications)
    blocks: list[dict[str, Any]]     # Rich Block Kit layout


class SlackClient:
    """
    Thin wrapper around Slack Incoming Webhooks.
    Instantiate once and reuse across the application.
    """

    def _post(self, payload: SlackPayload) -> bool:
        """
        Send a Block Kit payload to the Slack webhook URL.

        In MOCK_MODE prints the payload rather than making an HTTP call.
        Returns True on success, False on failure.
        """
        body = {"text": payload.text, "blocks": payload.blocks}

        if settings.MOCK_MODE:
            logger.info(
                "\n📨 [SLACK MOCK] → %s\n%s",
                payload.channel_url,
                json.dumps(body, indent=2, ensure_ascii=False),
            )
            return True

        try:
            resp = requests.post(
                payload.channel_url,
                json=body,
                timeout=5,
            )
            resp.raise_for_status()
            return True
        except requests.RequestException as exc:
            logger.error("Slack notification failed: %s", exc)
            return False

    # ------------------------------------------------------------------
    # Notification templates
    # ------------------------------------------------------------------

    def send_urgent_alert(
        self,
        sender_name: str,
        group_id: str,
        message_body: str,
        reasoning: str,
        suggested_reply: str | None = None,
    ) -> bool:
        """
        Post an URGENT WhatsApp alert to #alerts-urgent with an optional
        AI-generated reply suggestion produced by Claude Sonnet.
        """
        blocks: list[dict[str, Any]] = [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": "🚨 URGENT WhatsApp Alert"},
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*Sender:*\n{sender_name}"},
                    {"type": "mrkdwn", "text": f"*Group:*\n`{group_id}`"},
                ],
            },
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"*Message:*\n_{message_body}_"},
            },
            {
                "type": "context",
                "elements": [
                    {"type": "mrkdwn", "text": f"🤖 *AI Triage (Claude Sonnet):* {reasoning}"},
                ],
            },
        ]

        if suggested_reply:
            blocks.append({"type": "divider"})
            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"💬 *Suggested Reply (Claude Sonnet):*\n```{suggested_reply}```",
                },
            })

        return self._post(SlackPayload(
            channel_url=settings.SLACK_WEBHOOK_URGENT,
            text=f"🚨 URGENT from {sender_name}: {message_body[:80]}",
            blocks=blocks,
        ))

    def send_content_approval(
        self,
        keyword: str,
        blog_title: str,
        excerpt: str,
        wp_draft_url: str | None = None,
    ) -> bool:
        """
        Post a new SEO blog draft to #content-approval for human review
        before it is published to WordPress.

        Generated by Claude Opus as part of the SEO Keyword→Blog pipeline.
        """
        blocks: list[dict[str, Any]] = [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": "✍️ New SEO Content Draft — Approval Required"},
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*Target Keyword:*\n`{keyword}`"},
                    {"type": "mrkdwn", "text": f"*Title:*\n{blog_title}"},
                ],
            },
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"*Excerpt:*\n{excerpt}"},
            },
            {
                "type": "context",
                "elements": [
                    {"type": "mrkdwn", "text": "🧠 *Generated by:* Claude Opus — Deep SEO Reasoning"},
                ],
            },
        ]

        if wp_draft_url:
            blocks.append({
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "Review in WordPress"},
                        "url": wp_draft_url,
                        "style": "primary",
                    }
                ],
            })

        return self._post(SlackPayload(
            channel_url=settings.SLACK_WEBHOOK_CONTENT,
            text=f"✍️ New draft ready for approval: {blog_title}",
            blocks=blocks,
        ))

    def send_ad_recommendation(
        self,
        campaign_name: str,
        ad_id: str,
        current_ctr: float,
        split_test_ideas: list[str],
    ) -> bool:
        """
        Post AI-generated split test recommendations for underperforming
        Facebook campaigns to #ads-insights.

        Generated by Claude Sonnet for fast, cost-efficient copy ideation.
        """
        ideas_text = "\n".join(f"• {idea}" for idea in split_test_ideas)
        blocks: list[dict[str, Any]] = [
            {
                "type": "header",
                "text": {"type": "plain_text", "text": "💡 Ad Split-Test Recommendation"},
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*Campaign:*\n{campaign_name}"},
                    {"type": "mrkdwn", "text": f"*Ad ID:*\n`{ad_id}`"},
                    {"type": "mrkdwn", "text": f"*Current CTR:*\n{current_ctr:.2f}%"},
                ],
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*🤖 Claude Sonnet Suggestions:*\n{ideas_text}",
                },
            },
        ]

        return self._post(SlackPayload(
            channel_url=settings.SLACK_WEBHOOK_ADS,
            text=f"💡 Split-test ideas for '{campaign_name}' (CTR: {current_ctr:.2f}%)",
            blocks=blocks,
        ))


# Singleton — import this throughout the project
slack = SlackClient()
